version: "3"
services:
  postgresql:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on: 
      - posgresql
