version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure:10
    depends_on: 
      - postgresql
  postgresql:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password
